config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :questions
  root "dogs#index"
  resources :dogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    validates :name, :age, :breed, :description, :presence => true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :email, :subject, :message, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy]

  # GET /dogs or /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1 or /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to dog_url(@dog), notice: "Dog was successfully created." }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to dog_url(@dog), notice: "Dog was successfully updated." }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.destroy

    respond_to do |format|
      format.html { redirect_to dogs_url, notice: "Dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name, :age, :breed, :description)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show destroy]
  
  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to dogs_path, notice: "Message was successfully sent." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Message was successfully resolved." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:email, :subject, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    Submit
  <% end %>

<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<br>

<div class="btn btn-primary text-white">
    <%= link_to 'Show', @dog, :class => "btn text-white" %>
</div>

<div class="btn btn-primary text-white">
    <%= link_to 'Back', dogs_path, :class => "btn text-white" %>
</div>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid p-1 bg-primary text-white text-center">
  <ul class="nav">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Add a Dog', new_dog_path, :class => "btn text-white" %>
      </li>
    <% end %>
    <% if ! user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Contact the Shelter', new_question_path, :class => "btn text-white" %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'View Messages', questions_path, :class => "btn text-white" %>
      </li>
    <% end %>
  </ul>
</div>

<div class="container-fluid text-dark text-center">
  <h1>Colorado Springs Dog Shelter</h1>
</div>

<br>

<div class="container-fluid text-dark text-center">
  <div class="row">
    <% @dogs.each do |dog| %>
      <div class="col-md-3">
        <h1><%= dog.name %></h1>
        <div class="btn btn-primary text-white">
          <%= link_to 'Show', dog, :class => "btn text-white" %>
        </div>
        <% if user_signed_in? %>
          <div class="btn btn-primary text-white">
            <%= link_to 'Edit', edit_dog_path(dog), :class => "btn text-white" %>
          </div>
        <% end %>
        <% if user_signed_in? %>
          <div class="btn btn-primary text-white">
            <%= link_to 'Remove', dog, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn text-white" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<br>

<div class="btn btn-primary text-white">
  <%= link_to 'Back', dogs_path, :class => "btn text-white" %>
</div>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @dog.name %>
</h1>

<p>
  <strong>Age:</strong>
  <%= @dog.age %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dog.description %>
</p>

<div class="btn btn-primary text-white">
  <%= link_to 'Edit', edit_dog_path(@dog), :class => "btn text-white" %>
</div>
<div class="btn btn-primary text-white">
  <%= link_to 'Back', dogs_path, :class => "btn text-white" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300DogShelterProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Reply Email (required)" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label "Subject (required)" %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label "Message (required)" %>
    <%= form.text_area :message %>
  </div>

  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    Send Message
  <% end %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<br>

<div class="btn btn-primary text-white">
    <%= link_to 'Show', @question, :class => "btn text-white" %>
</div>

<div class="btn btn-primary text-white">
    <%= link_to 'Back', questions_path, :class => "btn text-white" %>
</div>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid p-1 bg-primary text-white text-center">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to 'Back', dogs_path, :class => "btn text-white" %>
    </li>
  </ul>
</div>

<div class="container-fluid text-dark text-center">
  <h1>Messages</h1>
</div>

<br>

<div class="container-fluid text-dark text-center">
  <div class="row">
    <% @questions.each do |question| %>
      <div class="col-md-3">
        <h1><%= question.subject %></h1>
        <div class="btn btn-primary text-white">
          <%= link_to 'Show', question, :class => "btn text-white" %>
        </div>
        <div class="btn btn-primary text-white">
          <%= link_to 'Mark Resolved', question, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn text-white" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h1>Contact the Shelter</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', dogs_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @question.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @question.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @question.message %>
</p>

<div class="btn btn-primary text-white">
  <%= link_to 'Back', questions_path, :class => "btn text-white" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>